# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'mysecretpassword'
  redis: 'myredispassword'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'Rc_FKFnto_mcK7LwboVwCbYeWj_SDcZo'

  emailSecretHashPepper: 'ekmlkNBalREzfAd5XmE0W8DiKna3j6cB'
  jwtHmacSha512PrivateKey: 'K_YbE_zmR__QJmpo0c9uY1iUvdUkxfuX'
  jwtRefreshTokenHashPepper: '17lWvPn5oIEKD1F4V_MmvipSrTb8dahc'
  # serverSideSessionKeyHashPepper: '2JuTmuwly-SJnBaTViBJUOQKzeYAkVQi'

test:
  database: '-RAsziYbOsseJnd5-m5rsldJiY4lXmId'
  redis: 'j94BC1l13DlnFixk29zKmCxHTd4xFV1l'

  emailSecretHashPepper: '4J-Q4pm0y3fFkqBt43WNFXGOKdNg5Hyk'
  jwtHmacSha512PrivateKey: 'XRLPkmrXErJQNgb9eovDo2M_VMkM4PPH'
  jwtRefreshTokenHashPepper: 'kKNEJ4tlG8gpc08wJZLS-E1UZbmEVPt8'
  # serverSideSessionKeyHashPepper: 'Qbucrm4UoleoYHT2XNiqMmX5CBkl_f2u'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'pKge7yoLOamhGITHL35aP5-06ba8OWKD'
  serviceSecret: '0jXCOcZCS7qfMjtoO1IYnAYLLHJy4fvx'

  emailSecretHashPepper: 'OYXb7on64x-bo_oJw4LQMDqpy8_YR-t2'
  jwtHmacSha512PrivateKey: 'hlWHaCQZXFmYMJraR2mmCet0DhPmbw_K'
  jwtRefreshTokenHashPepper: 'HHwc7mh3jTtP_O5WNmz3rIUyZbZz9PNc'
  # serverSideSessionKeyHashPepper: 'Hkx7NY-GaeEaXaOE9BtjavnyC1jIYq2o'

# Passwords used in production mode.
  database: 'nMIH4yoTKmYsRo5HrhrMEKtidqW08385'
  serviceSecret: 'gGhd9WTl_9Lf6hrLh7zYx1bLysrufXDc'

  emailSecretHashPepper: 'szFaZe7uGVZ0nZs9HAm99iHZXlM2nhLP'
  jwtHmacSha512PrivateKey: 'fLF332z2Ijwdj0-pdVk52TI1WYS1Qtmd'
  jwtRefreshTokenHashPepper: 't8fFPiDnaQmu1-dRwwQflA416ZKa2FN8'
  # serverSideSessionKeyHashPepper: 'JbzvfcPvN-SEIQmn7Mpxi3Aemi6KYUZi'
