# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

development:
  database: 'nMIH4yoTKmYsRo5HrhrMEKtidqW08385'
  redis: 'Ac4GAAIncDE3Yjk0ZmRjYTg3NmE0OWZlYmQxYzkzYjFjNzNkMTgzM3AxNTI3NDI'
  redis_url: 'https://mint-impala-52742.upstash.io'
  redis_token: 'Ac4GAAIncDE3Yjk0ZmRjYTg3NmE0OWZlYmQxYzkzYjFjNzNkMTgzM3AxNTI3NDI'
  serviceSecret: 'Rc_FKFnto_mcK7LwboVwCbYeWj_SDcZo'
  emailSecretHashPepper: 'ekmlkNBalREzfAd5XmE0W8DiKna3j6cB'
  jwtHmacSha512PrivateKey: 'K_YbE_zmR__QJmpo0c9uY1iUvdUkxfuX'
  jwtRefreshTokenHashPepper: '17lWvPn5oIEKD1F4V_MmvipSrTb8dahc'

test:
  database: 'nMIH4yoTKmYsRo5HrhrMEKtidqW08385'
  redis: 'Ac4GAAIncDE3Yjk0ZmRjYTg3NmE0OWZlYmQxYzkzYjFjNzNkMTgzM3AxNTI3NDI'
  redis_url: 'https://mint-impala-52742.upstash.io'
  redis_token: 'Ac4GAAIncDE3Yjk0ZmRjYTg3NmE0OWZlYmQxYzkzYjFjNzNkMTgzM3AxNTI3NDI'
  emailSecretHashPepper: '4J-Q4pm0y3fFkqBt43WNFXGOKdNg5Hyk'
  jwtHmacSha512PrivateKey: 'XRLPkmrXErJQNgb9eovDo2M_VMkM4PPH'
  jwtRefreshTokenHashPepper: 'kKNEJ4tlG8gpc08wJZLS-E1UZbmEVPt8'

staging:
  database: 'nMIH4yoTKmYsRo5HrhrMEKtidqW08385'
  redis: 'Ac4GAAIncDE3Yjk0ZmRjYTg3NmE0OWZlYmQxYzkzYjFjNzNkMTgzM3AxNTI3NDI'
  redis_url: 'https://mint-impala-52742.upstash.io'
  redis_token: 'Ac4GAAIncDE3Yjk0ZmRjYTg3NmE0OWZlYmQxYzkzYjFjNzNkMTgzM3AxNTI3NDI'
  serviceSecret: '0jXCOcZCS7qfMjtoO1IYnAYLLHJy4fvx'
  emailSecretHashPepper: 'OYXb7on64x-bo_oJw4LQMDqpy8_YR-t2'
  jwtHmacSha512PrivateKey: 'hlWHaCQZXFmYMJraR2mmCet0DhPmbw_K'
  jwtRefreshTokenHashPepper: 'HHwc7mh3jTtP_O5WNmz3rIUyZbZz9PNc'

production:
  database: 'nMIH4yoTKmYsRo5HrhrMEKtidqW08385'
  redis: 'Ac4GAAIncDE3Yjk0ZmRjYTg3NmE0OWZlYmQxYzkzYjFjNzNkMTgzM3AxNTI3NDI'
  redis_url: 'https://mint-impala-52742.upstash.io'
  redis_token: 'Ac4GAAIncDE3Yjk0ZmRjYTg3NmE0OWZlYmQxYzkzYjFjNzNkMTgzM3AxNTI3NDI'
  serviceSecret: 'gGhd9WTl_9Lf6hrLh7zYx1bLysrufXDc'
  emailSecretHashPepper: 'szFaZe7uGVZ0nZs9HAm99iHZXlM2nhLP'
  jwtHmacSha512PrivateKey: 'fLF332z2Ijwdj0-pdVk52TI1WYS1Qtmd'
  jwtRefreshTokenHashPepper: 't8fFPiDnaQmu1-dRwwQflA416ZKa2FN8'
