# This is the configuration file for your test environment.
# All ports are set to zero in this file which makes the server find the next available port.
# This is needed to enable running tests concurrently. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API test server.
apiServer:
  port: 0
  publicHost: localhost
  publicPort: 0
  publicScheme: http

# Configuration for the Insights test server.
insightsServer:
  port: 0
  publicHost: localhost
  publicPort: 0
  publicScheme: http

# Configuration for the web test server.
webServer:
  port: 0
  publicHost: localhost
  publicPort: 0
  publicScheme: http

database:
  host: dpg-d5tq1lqli9vc73a0gbq0-a
  port: 5432
  name: resonate_db_tjbk
  user: resonatedb_u99l_user
  requireSsl: true

# This is the setup for your Redis test instance.
redis:
  enabled: true
  host: mint-impala-52742.upstash.io
  port: 6379
  requireSsl: true

sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
# consoleLogFormat: json # Defaults to "json", options are "text" or "json"

# futureCallExecutionEnabled: true # Defaults to true

#futureCall:
#  concurrencyLimit: 1 # Defaults to 1, a negative or null value removes the limit
#  scanInterval: 5000 # Unit in milliseconds, defaults to 5000
