# Database credentials for Serverpod (Render.com example)

postgres:
  host: dpg-d5tq1lqli9vc73a0gbq0-a
  port: 5432
  user: resonate_db_tjbk_user
  password: CVWmzIUFtmmAG5EWk8GVfR9oPBBeWewC
  databaseName: resonate_db_tjbk

# Upstash Redis credentials
redis:
  url: https://mint-impala-52742.upstash.io
  token: Ac4GAAIncDE3Yjk0ZmRjYTg3NmE0OWZlYmQxYzkzYjFjNzNkMTgzM3AxNTI3NDI
